### ISSUE TITLE
I would like to see a recent activity feed

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#489]
Fred Jones signed up for Something Something (time / date)
“this is great!” said [Judy Smith](link/to/profile) on [Kids.gov Twitter](link/to/task)  (time / date)
Jody Tuan posted a new opportunity: "Stuff Should Happen!"
Tom Smith updated his profile (time / date)
Betty Rubble joined! (time / date)

**Comment by ultrasaurus** [comment]
Let's do this iteratively, with one type of event at a time.

**Comment by dhcole** [comment]
We can get most of what we need from the `notification` table. By using this data, we can create a feed of recent events with populated data for the related models (e.g. users, tasks, projects).

Here is the data we need for the feed, keyed by the matching action in the `notification` table.

## Events
1. **taskVolunteerAdded**
  - example: `Fred Jones signed up for Something Something (time / date)`
  - template: `[user.name] signed up for [task.title]`
  - data: `user, task`
2. **taskCommentAdded** 
  - example: `“this is great!” said [Judy Smith](link/to/profile) on [Kids.gov Twitter](link/to/task)  (time / date)`
  - template: `[comment.value] said [User(comment.userId).name, .id] on [task.title]`
  - data: `comment, user(comment.userId), task`
3. **projectCommentAdded**
  - example: `“this is great!” said [Judy Smith](link/to/profile) on [Kids.gov Twitter](link/to/project)  (time / date)`
  - template: `[comment.value] said [User(comment.userId).name, .id] on [project.title]`
  - data: `comment, user(comment.userId), project`
4. **welcomeUser**
  - example: `Betty Rubble joined! (time / date)`
  - template: `[user.name] joined!`
  - data: `[user]`
4. **tackCreated** *Doesn't exist yet*
  - example: `Jody Tuan posted a new opportunity: "Stuff Should Happen!”`
  - template: `[user.name] posted a new opportunity: “[task.title]”`
  - data: `user, task`
5. **userUpdated** *Doesn't exist yet*
  - example: `Tom Smith updated his profile (time / date)`
  - template: `Profile update: [user.name] updated their profile`
  - data: `user`

And here are the tasks to build this.

## Tasks
- [ ] Set up `/api/admin/activities` feed of events with populated models
- [ ] Set up front-end template to format feed on `/admin/dashboard`
- [ ] Add new notification actions for **tackCreated** and **userUpdated**, which shouldn't send emails

**Comment by dhcole** [comment]
Activity feed and front end are now working in #495 

![screen shot 2015-01-15 at 12 36 52 pm](https://cloud.githubusercontent.com/assets/170641/5762833/4e2c7462-9cb3-11e4-9c12-e5160c059145.png)

**Comment by ultrasaurus** [comment]
this is so exciting!  What happens if someone doesn't have a username?

**Comment by dhcole** [comment]
Right now, it's just using `user.name`. I can have it fall back to `user.username`, which is email address. Sound good?
