### ISSUE TITLE
As a user, my session should persist across server restarts

### ISSUE THREAD

**Issue by dhcole** [18F/midas#496]
Currently, we're using the server's memory to store user sessions. This means if a server restarts, which happens during each code update, the sessions are erased, and all users need to log back in. This also means during development, developers need to log in each time they test new code.

A better way to go is to use a shared session store that persists across restarts. This would also open up the possibility of sharing sessions across multiple servers for a redundant / autoscaling cluster of web servers.

## Tasks

- [ ] find a shared session store we can use. Common options are redis, mongodb. Not sure what we can use from the AWS stack
- [ ] update [session configuration](https://github.com/18F/midas/blob/devel/config/session.js) to use the new store
- [ ] set a desired time for sessions to expire. Currently sessions also expire each time the browser is closed.
